version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: ./dockerfile
    image: felipe6090/cdlp-web
    ports:
      - "3000:3000"
    command: sh -c '../wait-for.sh cdlp-back-end:4000 -- echo "succes back-end process"'
    depends_on:
      - "back-end"
    container_name: cdlp-web

  back-end:
    build:
      context: ./back-end
      dockerfile: ./dockerfile
    environment:
      - DATABASE_URL="mysql://root:root@localhost:3306/mydb?schema=public"
    image: felipe6090/cdlp-back-end
    ports:
      - "4000:4000"
    command: sh -c '../wait-for.sh cdlp-mysql:4000 -- echo "succes back-end process"'
    depends_on:
      - "mysql"
    container_name: cdlp-back-end

  mysql:
    image: mysql:5.7
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    container_name: cdlp-mysql

volumes:
  data-volume:
