FROM node:latest as packages
WORKDIR /packages
COPY package.json .
RUN npm install

FROM node:latest
WORKDIR /main/web
COPY . .
COPY --from=packages /packages/node_modules node_modules
RUN ["npm", "run", "build"]
ENTRYPOINT ["npm", "run", "start"]  
EXPOSE 3000