FROM node:latest as packages
WORKDIR /packages
COPY package.json .
RUN npm install

FROM node:latest
WORKDIR /main/web
COPY . .
COPY --from=packages /packages/node_modules node_modules
RUN ["chmod", "+x", "./docker-entrypoints.sh"]
ENTRYPOINT ["./docker-entrypoints.sh"] 
EXPOSE 3000